// Mock ATP Players with realistic data
export const mockPlayers = [
  {
    id: 1,
    name: 'Novak Djokovic',
    rank: 1,
    country: 'Serbia',
    age: 36,
    points: 0,
    recentForm: { winRate: 0.85, wins: 17, losses: 3 },
  },
  {
    id: 2,
    name: 'Carlos Alcaraz',
    rank: 2,
    country: 'Spain',
    age: 20,
    points: 0,
    recentForm: { winRate: 0.80, wins: 16, losses: 4 },
  },
  {
    id: 3,
    name: 'Daniil Medvedev',
    rank: 3,
    country: 'Russia',
    age: 27,
    points: 0,
    recentForm: { winRate: 0.75, wins: 15, losses: 5 },
  },
  {
    id: 4,
    name: 'Jannik Sinner',
    rank: 4,
    country: 'Italy',
    age: 22,
    points: 0,
    recentForm: { winRate: 0.78, wins: 14, losses: 4 },
  },
  {
    id: 5,
    name: 'Andrey Rublev',
    rank: 5,
    country: 'Russia',
    age: 26,
    points: 0,
    recentForm: { winRate: 0.72, wins: 13, losses: 5 },
  },
  {
    id: 6,
    name: 'Stefanos Tsitsipas',
    rank: 6,
    country: 'Greece',
    age: 25,
    points: 0,
    recentForm: { winRate: 0.70, wins: 14, losses: 6 },
  },
  {
    id: 7,
    name: 'Holger Rune',
    rank: 7,
    country: 'Denmark',
    age: 20,
    points: 0,
    recentForm: { winRate: 0.68, wins: 13, losses: 6 },
  },
  {
    id: 8,
    name: 'Casper Ruud',
    rank: 8,
    country: 'Norway',
    age: 25,
    points: 0,
    recentForm: { winRate: 0.71, wins: 12, losses: 5 },
  },
  {
    id: 9,
    name: 'Hubert Hurkacz',
    rank: 9,
    country: 'Poland',
    age: 26,
    points: 0,
    recentForm: { winRate: 0.65, wins: 11, losses: 6 },
  },
  {
    id: 10,
    name: 'Taylor Fritz',
    rank: 10,
    country: 'USA',
    age: 26,
    points: 0,
    recentForm: { winRate: 0.67, wins: 12, losses: 6 },
  },
  {
    id: 11,
    name: 'Alex de Minaur',
    rank: 11,
    country: 'Australia',
    age: 24,
    points: 0,
    recentForm: { winRate: 0.64, wins: 11, losses: 6 },
  },
  {
    id: 12,
    name: 'Tommy Paul',
    rank: 12,
    country: 'USA',
    age: 26,
    points: 0,
    recentForm: { winRate: 0.62, wins: 10, losses: 6 },
  },
  {
    id: 13,
    name: 'Alexander Zverev',
    rank: 13,
    country: 'Germany',
    age: 26,
    points: 0,
    recentForm: { winRate: 0.69, wins: 13, losses: 6 },
  },
  {
    id: 14,
    name: 'Frances Tiafoe',
    rank: 14,
    country: 'USA',
    age: 25,
    points: 0,
    recentForm: { winRate: 0.60, wins: 9, losses: 6 },
  },
  {
    id: 15,
    name: 'Karen Khachanov',
    rank: 15,
    country: 'Russia',
    age: 27,
    points: 0,
    recentForm: { winRate: 0.63, wins: 10, losses: 6 },
  },
  {
    id: 16,
    name: 'Cameron Norrie',
    rank: 16,
    country: 'Great Britain',
    age: 28,
    points: 0,
    recentForm: { winRate: 0.58, wins: 9, losses: 7 },
  },
  {
    id: 17,
    name: 'Ugo Humbert',
    rank: 17,
    country: 'France',
    age: 25,
    points: 0,
    recentForm: { winRate: 0.61, wins: 11, losses: 7 },
  },
  {
    id: 18,
    name: 'Lorenzo Musetti',
    rank: 18,
    country: 'Italy',
    age: 21,
    points: 0,
    recentForm: { winRate: 0.59, wins: 10, losses: 7 },
  },
  {
    id: 19,
    name: 'Adrian Mannarino',
    rank: 19,
    country: 'France',
    age: 35,
    points: 0,
    recentForm: { winRate: 0.55, wins: 8, losses: 7 },
  },
  {
    id: 20,
    name: 'Sebastian Baez',
    rank: 20,
    country: 'Argentina',
    age: 23,
    points: 0,
    recentForm: { winRate: 0.57, wins: 9, losses: 7 },
  },
  // Add more mid-tier players
  {
    id: 21,
    name: 'Nicolas Jarry',
    rank: 21,
    country: 'Chile',
    age: 28,
    points: 0,
    recentForm: { winRate: 0.56, wins: 8, losses: 6 },
  },
  {
    id: 22,
    name: 'Alejandro Tabilo',
    rank: 22,
    country: 'Chile',
    age: 26,
    points: 0,
    recentForm: { winRate: 0.54, wins: 7, losses: 6 },
  },
  {
    id: 23,
    name: 'Ben Shelton',
    rank: 23,
    country: 'USA',
    age: 21,
    points: 0,
    recentForm: { winRate: 0.60, wins: 9, losses: 6 },
  },
  {
    id: 24,
    name: 'Jan-Lennard Struff',
    rank: 24,
    country: 'Germany',
    age: 33,
    points: 0,
    recentForm: { winRate: 0.52, wins: 7, losses: 6 },
  },
  // Low tier players
  {
    id: 25,
    name: 'Alexei Popyrin',
    rank: 40,
    country: 'Australia',
    age: 24,
    points: 0,
    recentForm: { winRate: 0.50, wins: 6, losses: 6 },
  },
  {
    id: 26,
    name: 'Thanasi Kokkinakis',
    rank: 65,
    country: 'Australia',
    age: 27,
    points: 0,
    recentForm: { winRate: 0.48, wins: 5, losses: 6 },
  },
  {
    id: 27,
    name: 'Christopher Eubanks',
    rank: 80,
    country: 'USA',
    age: 27,
    points: 0,
    recentForm: { winRate: 0.45, wins: 4, losses: 5 },
  },
  {
    id: 28,
    name: 'Rinky Hijikata',
    rank: 95,
    country: 'Australia',
    age: 22,
    points: 0,
    recentForm: { winRate: 0.42, wins: 4, losses: 6 },
  },
];

// Mock tournaments
export const mockTournaments = [
  {
    id: 1,
    name: 'Australian Open',
    date: 'January 14-28, 2024',
    startDate: '2024-01-14',
    endDate: '2024-01-28',
    surface: 'Hard Court',
    status: 'Active',
    currentRound: 1,
    userPoints: 0,
  },
  {
    id: 2,
    name: 'French Open',
    date: 'May 26 - June 9, 2024',
    startDate: '2024-05-26',
    endDate: '2024-06-09',
    surface: 'Clay',
    status: 'Upcoming',
    currentRound: 0,
    userPoints: 0,
  },
  {
    id: 3,
    name: 'Wimbledon',
    date: 'July 1-14, 2024',
    startDate: '2024-07-01',
    endDate: '2024-07-14',
    surface: 'Grass',
    status: 'Upcoming',
    currentRound: 0,
    userPoints: 0,
  },
  {
    id: 4,
    name: 'US Open',
    date: 'August 26 - September 8, 2024',
    startDate: '2024-08-26',
    endDate: '2024-09-08',
    surface: 'Hard Court',
    status: 'Upcoming',
    currentRound: 0,
    userPoints: 0,
  },
];

// Mock match results for simulation
export const mockMatchResults = [
  {
    id: 1,
    playerId: 23, // Ben Shelton (rank 23)
    opponentId: 3, // Beat Medvedev (rank 3)
    opponentRank: 3,
    playerRank: 23,
    won: true,
    stats: {
      won: true,
      aces: 15,
      doubleFaults: 3,
      breakPointsConverted: 4,
      serviceGamesWon: 12,
      setsWon: 3,
      setsLost: 2,
    },
    round: 1,
  },
  {
    id: 2,
    playerId: 1, // Djokovic won
    opponentId: 28,
    opponentRank: 95,
    playerRank: 1,
    won: true,
    stats: {
      won: true,
      aces: 8,
      doubleFaults: 1,
      breakPointsConverted: 5,
      serviceGamesWon: 15,
      setsWon: 3,
      setsLost: 0, // Straight sets = dominant win
    },
    round: 1,
  },
  {
    id: 3,
    playerId: 2, // Alcaraz won
    opponentId: 27,
    opponentRank: 80,
    playerRank: 2,
    won: true,
    stats: {
      won: true,
      aces: 10,
      doubleFaults: 2,
      breakPointsConverted: 6,
      serviceGamesWon: 14,
      setsWon: 3,
      setsLost: 1,
    },
    round: 1,
  },
];

// Helper function to simulate match completion
export const simulateMatchCompletion = (playerId) => {
  return mockMatchResults.find(match => match.playerId === playerId);
};